name: Kernel Build (d2s only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_d2s:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source (full history + submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.EM }}

      - name: Fix submodule state (deterministic)
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force

      - name: Get KernelSU version
        id: ksu
        run: |
          cd KernelSU-Next

          COUNT=$(git rev-list --count HEAD)
          VERSION=$((30000 + COUNT + 150))

          echo "count=$COUNT" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          echo "KernelSU commit:"
          git log -1 --oneline

          echo "KernelSU version:"
          echo $VERSION

      - name: Clean build directory
        run: |
          rm -rf build/out
          mkdir -p build/out

      - name: Build d2s kernel
        run: |
          chmod +x ./workflows.sh
          ./workflows.sh -m d2s -k Y -r N

      - name: Upload artifact (with KSU version)
        uses: actions/upload-artifact@v4
        with:
          name: ExtremeKRNL-Nexus-d2s-KSU${{ steps.ksu.outputs.version }}
          path: build/out/d2s/zip
