name: Update KernelSU-Next Submodule Pointer

on:
  push: 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          token: ${{ secrets.EM }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Authenticate remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.EM }}@github.com/${{ github.repository }}

      - name: Sync submodule
        run: git submodule sync --recursive

      - name: Initialize submodule
        run: |
          git submodule update --init --force --recursive KernelSU-Next

      - name: Update KernelSU-Next pointer
        run: |
          cd KernelSU-Next

          git fetch origin

          git checkout fc33995cedc5e0ebf719745c71fe15e78694260f

          cd ..

      - name: Commit updated pointer
        run: |
          git add KernelSU-Next

          git commit -m "KernelSU-Next: bump to fc33995" || echo "No changes to commit"

          git push origin HEAD:main
